'use client';

import React, { useState, useCallback } from 'react';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface ExportFormat {
  id: 'csv' | 'excel' | 'pdf' | 'json';
  name: string;
  description: string;
  icon: string;
  mimeType: string;
  extension: string;
}

interface ExportOptions {
  format: ExportFormat['id'];
  includeHeaders: boolean;
  includeMetadata: boolean;
  dateFormat: 'iso' | 'local' | 'custom';
  customDateFormat?: string;
  numberFormat: 'raw' | 'formatted' | 'currency';
  pageOrientation?: 'portrait' | 'landscape';
  pageSize?: 'a4' | 'letter' | 'legal';
  compression?: boolean;
}

interface ReportExporterProps {
  data: any[];
  reportName: string;
  reportMetadata?: {
    generatedAt: Date;
    generatedBy: string;
    description?: string;
    filters?: Record<string, any>;
    totalRecords: number;
  };
  onExportStart?: (format: ExportFormat['id']) => void;
  onExportComplete?: (format: ExportFormat['id'], success: boolean) => void;
  onExportError?: (error: Error) => void;
  className?: string;
}

const EXPORT_FORMATS: ExportFormat[] = [
  {
    id: 'csv',
    name: 'CSV',
    description: 'Comma-separated values file',
    icon: '📄',
    mimeType: 'text/csv',
    extension: 'csv'
  },
  {
    id: 'excel',
    name: 'Excel',
    description: 'Microsoft Excel spreadsheet',
    icon: '📊',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    extension: 'xlsx'
  },
  {
    id: 'pdf',
    name: 'PDF',
    description: 'Portable Document Format',
    icon: '📋',
    mimeType: 'application/pdf',
    extension: 'pdf'
  },
  {
    id: 'json',
    name: 'JSON',
    description: 'JavaScript Object Notation',
    icon: '🔧',
    mimeType: 'application/json',
    extension: 'json'
  }
];

export function ReportExporter({
  data,
  reportName,
  reportMetadata,
  onExportStart,
  onExportComplete,
  onExportError,
  className = ''
}: ReportExporterProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportOptions, setExportOptions] = useState<ExportOptions>({
    format: 'csv',
    includeHeaders: true,
    includeMetadata: true,
    dateFormat: 'local',
    numberFormat: 'formatted',
    pageOrientation: 'portrait',
    pageSize: 'a4',
    compression: false
  });
  const [showOptions, setShowOptions] = useState(false);

  // Format data based on options
  const formatData = useCallback((rawData: any[], options: ExportOptions) => {
    if (!rawData || rawData.length === 0) return [];

    return rawData.map(row => {
      const formattedRow: any = {};
      
      Object.entries(row).forEach(([key, value]) => {
        if (value instanceof Date) {
          switch (options.dateFormat) {
            case 'iso':
              formattedRow[key] = value.toISOString();
              break;
            case 'local':
              formattedRow[key] = value.toLocaleDateString();
              break;
            case 'custom':
              formattedRow[key] = options.customDateFormat 
                ? value.toLocaleDateString('en-US', { 
                    year: 'numeric', 
                    month: '2-digit', 
                    day: '2-digit' 
                  })
                : value.toLocaleDateString();
              break;
            default:
              formattedRow[key] = value;
          }
        } else if (typeof value === 'number') {
          switch (options.numberFormat) {
            case 'raw':
              formattedRow[key] = value;
              break;
            case 'formatted':
              formattedRow[key] = value.toLocaleString();
              break;
            case 'currency':
              formattedRow[key] = new Intl.NumberFormat('en-US', {
                style: 'currency',
                currency: 'USD'
              }).format(value);
              break;
            default:
              formattedRow[key] = value;
          }
        } else {
          formattedRow[key] = value;
        }
      });

      return formattedRow;
    });
  }, []);

  // Generate CSV
  const generateCSV = useCallback((data: any[], options: ExportOptions) => {
    const formattedData = formatData(data, options);
    
    if (formattedData.length === 0) return '';

    const headers = Object.keys(formattedData[0]);
    let csv = '';

    // Add metadata if requested
    if (options.includeMetadata && reportMetadata) {
      csv += `Report: ${reportName}\n`;
      csv += `Generated: ${reportMetadata.generatedAt.toLocaleString()}\n`;
      csv += `Generated By: ${reportMetadata.generatedBy}\n`;
      if (reportMetadata.description) {
        csv += `Description: ${reportMetadata.description}\n`;
      }
      csv += `Total Records: ${reportMetadata.totalRecords}\n`;
      csv += '\n';
    }

    // Add headers
    if (options.includeHeaders) {
      csv += headers.join(',') + '\n';
    }

    // Add data rows
    formattedData.forEach(row => {
      const values = headers.map(header => {
        const value = row[header];
        // Escape commas and quotes in CSV
        if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
          return `"${value.replace(/"/g, '""')}"`;
        }
        return value || '';
      });
      csv += values.join(',') + '\n';
    });

    return csv;
  }, [formatData, reportName, reportMetadata]);

  // Generate Excel
  const generateExcel = useCallback((data: any[], options: ExportOptions) => {
    const formattedData = formatData(data, options);
    const workbook = XLSX.utils.book_new();
    
    // Create main data worksheet
    const worksheet = XLSX.utils.json_to_sheet(formattedData, {
      header: options.includeHeaders ? undefined : []
    });

    // Add metadata worksheet if requested
    if (options.includeMetadata && reportMetadata) {
      const metadataSheet = XLSX.utils.aoa_to_sheet([
        ['Report Name', reportName],
        ['Generated At', reportMetadata.generatedAt.toLocaleString()],
        ['Generated By', reportMetadata.generatedBy],
        ['Description', reportMetadata.description || ''],
        ['Total Records', reportMetadata.totalRecords],
        ['Filters', JSON.stringify(reportMetadata.filters || {})]
      ]);
      XLSX.utils.book_append_sheet(workbook, metadataSheet, 'Metadata');
    }

    XLSX.utils.book_append_sheet(workbook, worksheet, 'Report Data');
    
    return XLSX.write(workbook, { 
      bookType: 'xlsx', 
      type: 'array',
      compression: options.compression 
    });
  }, [formatData, reportName, reportMetadata]);

  // Generate PDF
  const generatePDF = useCallback((data: any[], options: ExportOptions) => {
    const formattedData = formatData(data, options);
    
    const doc = new jsPDF({
      orientation: options.pageOrientation || 'portrait',
      unit: 'mm',
      format: options.pageSize || 'a4'
    });

    // Add title
    doc.setFontSize(16);
    doc.text(reportName, 20, 20);

    let yPosition = 30;

    // Add metadata if requested
    if (options.includeMetadata && reportMetadata) {
      doc.setFontSize(10);
      doc.text(`Generated: ${reportMetadata.generatedAt.toLocaleString()}`, 20, yPosition);
      yPosition += 5;
      doc.text(`Generated By: ${reportMetadata.generatedBy}`, 20, yPosition);
      yPosition += 5;
      if (reportMetadata.description) {
        doc.text(`Description: ${reportMetadata.description}`, 20, yPosition);
        yPosition += 5;
      }
      doc.text(`Total Records: ${reportMetadata.totalRecords}`, 20, yPosition);
      yPosition += 10;
    }

    // Add table
    if (formattedData.length > 0) {
      const headers = Object.keys(formattedData[0]);
      const tableData = formattedData.map(row => 
        headers.map(header => String(row[header] || ''))
      );

      doc.autoTable({
        head: options.includeHeaders ? [headers] : undefined,
        body: tableData,
        startY: yPosition,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [66, 139, 202] },
        margin: { top: 20, right: 20, bottom: 20, left: 20 }
      });
    }

    return doc.output('arraybuffer');
  }, [formatData, reportName, reportMetadata]);

  // Generate JSON
  const generateJSON = useCallback((data: any[], options: ExportOptions) => {
    const formattedData = formatData(data, options);
    
    const exportData: any = {
      data: formattedData
    };

    if (options.includeMetadata && reportMetadata) {
      exportData.metadata = {
        reportName,
        generatedAt: reportMetadata.generatedAt.toISOString(),
        generatedBy: reportMetadata.generatedBy,
        description: reportMetadata.description,
        totalRecords: reportMetadata.totalRecords,
        filters: reportMetadata.filters
      };
    }

    return JSON.stringify(exportData, null, 2);
  }, [formatData, reportName, reportMetadata]);

  // Download file
  const downloadFile = useCallback((content: any, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    URL.revokeObjectURL(url);
  }, []);

  // Handle export
  const handleExport = useCallback(async (format: ExportFormat['id']) => {
    if (isExporting) return;

    setIsExporting(true);
    onExportStart?.(format);

    try {
      const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, '-');
      const filename = `${reportName}_${timestamp}`;
      
      let content: any;
      let mimeType: string;
      let extension: string;

      switch (format) {
        case 'csv':
          content = generateCSV(data, exportOptions);
          mimeType = 'text/csv';
          extension = 'csv';
          break;
        case 'excel':
          content = generateExcel(data, exportOptions);
          mimeType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
          extension = 'xlsx';
          break;
        case 'pdf':
          content = generatePDF(data, exportOptions);
          mimeType = 'application/pdf';
          extension = 'pdf';
          break;
        case 'json':
          content = generateJSON(data, exportOptions);
          mimeType = 'application/json';
          extension = 'json';
          break;
        default:
          throw new Error(`Unsupported format: ${format}`);
      }

      downloadFile(content, `${filename}.${extension}`, mimeType);
      onExportComplete?.(format, true);
    } catch (error) {
      console.error('Export failed:', error);
      onExportError?.(error as Error);
      onExportComplete?.(format, false);
    } finally {
      setIsExporting(false);
    }
  }, [
    isExporting,
    data,
    exportOptions,
    reportName,
    generateCSV,
    generateExcel,
    generatePDF,
    generateJSON,
    downloadFile,
    onExportStart,
    onExportComplete,
    onExportError
  ]);

  return (
    <div className={`report-exporter ${className}`}>
      {/* Export Buttons */}
      <div className="flex flex-wrap gap-3 mb-4">
        {EXPORT_FORMATS.map((format) => (
          <button
            key={format.id}
            onClick={() => handleExport(format.id)}
            disabled={isExporting || data.length === 0}
            className="flex items-center space-x-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            <span className="text-lg">{format.icon}</span>
            <span>Export {format.name}</span>
            {isExporting && (
              <div className="w-4 h-4 border-2 border-gray-300 border-t-blue-600 rounded-full animate-spin"></div>
            )}
          </button>
        ))}
      </div>

      {/* Export Options Toggle */}
      <div className="mb-4">
        <button
          onClick={() => setShowOptions(!showOptions)}
          className="flex items-center space-x-2 text-sm text-primary hover:text-primary-dark transition-colors"
        >
          <span>Export Options</span>
          <svg
            className={`w-4 h-4 transition-transform ${showOptions ? 'rotate-180' : ''}`}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>
      </div>

      {/* Export Options Panel */}
      {showOptions && (
        <div className="bg-gray-50 rounded-lg p-4 space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Include Headers */}
            <div className="flex items-center space-x-3">
              <input
                type="checkbox"
                id="include-headers"
                checked={exportOptions.includeHeaders}
                onChange={(e) => setExportOptions(prev => ({
                  ...prev,
                  includeHeaders: e.target.checked
                }))}
                className="h-4 w-4 text-primary focus:ring-primary border-gray-300 rounded"
              />
              <label htmlFor="include-headers" className="text-sm font-medium text-gray-700">
                Include Headers
              </label>
            </div>

            {/* Include Metadata */}
            <div className="flex items-center space-x-3">
              <input
                type="checkbox"
                id="include-metadata"
                checked={exportOptions.includeMetadata}
                onChange={(e) => setExportOptions(prev => ({
                  ...prev,
                  includeMetadata: e.target.checked
                }))}
                className="h-4 w-4 text-primary focus:ring-primary border-gray-300 rounded"
              />
              <label htmlFor="include-metadata" className="text-sm font-medium text-gray-700">
                Include Metadata
              </label>
            </div>

            {/* Date Format */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Date Format</label>
              <select
                value={exportOptions.dateFormat}
                onChange={(e) => setExportOptions(prev => ({
                  ...prev,
                  dateFormat: e.target.value as any
                }))}
                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
              >
                <option value="iso">ISO Format</option>
                <option value="local">Local Format</option>
                <option value="custom">Custom Format</option>
              </select>
            </div>

            {/* Number Format */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Number Format</label>
              <select
                value={exportOptions.numberFormat}
                onChange={(e) => setExportOptions(prev => ({
                  ...prev,
                  numberFormat: e.target.value as any
                }))}
                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
              >
                <option value="raw">Raw Numbers</option>
                <option value="formatted">Formatted</option>
                <option value="currency">Currency</option>
              </select>
            </div>

            {/* PDF Options */}
            {exportOptions.format === 'pdf' && (
              <>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Page Orientation</label>
                  <select
                    value={exportOptions.pageOrientation}
                    onChange={(e) => setExportOptions(prev => ({
                      ...prev,
                      pageOrientation: e.target.value as any
                    }))}
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
                  >
                    <option value="portrait">Portrait</option>
                    <option value="landscape">Landscape</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Page Size</label>
                  <select
                    value={exportOptions.pageSize}
                    onChange={(e) => setExportOptions(prev => ({
                      ...prev,
                      pageSize: e.target.value as any
                    }))}
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
                  >
                    <option value="a4">A4</option>
                    <option value="letter">Letter</option>
                    <option value="legal">Legal</option>
                  </select>
                </div>
              </>
            )}

            {/* Compression */}
            {(exportOptions.format === 'excel' || exportOptions.format === 'json') && (
              <div className="flex items-center space-x-3">
                <input
                  type="checkbox"
                  id="compression"
                  checked={exportOptions.compression}
                  onChange={(e) => setExportOptions(prev => ({
                    ...prev,
                    compression: e.target.checked
                  }))}
                  className="h-4 w-4 text-primary focus:ring-primary border-gray-300 rounded"
                />
                <label htmlFor="compression" className="text-sm font-medium text-gray-700">
                  Enable Compression
                </label>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Export Status */}
      {data.length === 0 && (
        <div className="text-sm text-gray-500 mt-2">
          No data available for export
        </div>
      )}
    </div>
  );
}